### ISSUE TITLE
game crash when discussing hackathon with Annika (on August 4)

### ISSUE THREAD

**Issue by SHANbic** [freeCodeCamp/LearnToCodeRPG#29] opened 2021-12-26 22:19 UTC
### What bug did you encounter?

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 817, in script call
    call ask_hackathon from _call_ask_hackathon
  File "game/scripts/labels/npc_question_and_answer.rpy", line 51, in script
    $ topics_to_ask.remove('Hackathon')
  File "game/scripts/labels/npc_question_and_answer.rpy", line 51, in <module>
    $ topics_to_ask.remove('Hackathon')
KeyError: u'Hackathon'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 817, in script call
    call ask_hackathon from _call_ask_hackathon
  File "game/scripts/labels/npc_question_and_answer.rpy", line 51, in script
    $ topics_to_ask.remove('Hackathon')
  File "/Users/lambert_pierre/Desktop/LearnToCodeRPG.app/Contents/Resources/autorun/renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/lambert_pierre/Desktop/LearnToCodeRPG.app/Contents/Resources/autorun/renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/labels/npc_question_and_answer.rpy", line 51, in <module>
    $ topics_to_ask.remove('Hackathon')
  File "/Users/lambert_pierre/Desktop/LearnToCodeRPG.app/Contents/Resources/autorun/renpy/python.py", line 875, in do_mutation
    return method(self, *args, **kwargs)
KeyError: u'Hackathon'

Darwin-19.6.0-x86_64-i386-64bit
Ren'Py 7.4.8.1895
Learn to Code RPG 1.0
Sun Dec 26 23:12:25 2021
[/code]

### Steps to Reproduce

on the 4th of August, ask Annika about Hackathon to eventually have the game crashing at some point in the discussion. Unfortunately, it appears you can't really avoid it as the "That's everything I need to know" option is not clickable.

**Comment by RuolinZheng08** [comment] 2021-12-27 00:13
Duplicate of #14. Fixed. 
Please feel free to download the updated version from itch. Your saved game should carry over without a problem.

**Closed by RuolinZheng08** 2021-12-27 00:13 UTC
