### ISSUE TITLE
Help me understand

### ISSUE THREAD

**Issue by anrizald** [freeCodeCamp/LearnToCodeRPG#13] opened 2021-12-23 19:22 UTC
can someone clarify if third option and fourth option are different? 

![image](https://user-images.githubusercontent.com/73733261/147283741-328440cb-2e2f-4f8a-a12b-17b84dcf6703.png)

**Comment by RuolinZheng08** [comment] 2021-12-23 23:13
<img width="1290" alt="Screen Shot 2021-12-23 at 15 11 08" src="https://user-images.githubusercontent.com/35674052/147298609-f1cb9ff2-b5bc-4a57-b119-617f63b422ea.png">
Caused by some `\n` and `\r` that we forgot to escape. Fixed in https://github.com/freeCodeCamp/LearnToCodeRPG/commit/ee401e47790b2f8b8c1164c666e0e25c64231076

Thanks!

**Closed by RuolinZheng08** 2021-12-23 23:13 UTC
