### ISSUE TITLE
misquoting when taking a day off

### ISSUE THREAD

**Issue by alandgmendes** [freeCodeCamp/LearnToCodeRPG#11] opened 2021-12-23 17:16 UTC
### What bug did you encounter?

character thinking about working at the caffe when i had walked around the park

### Steps to Reproduce

on day 9 i took a break, went to the park, and when i came back home, i wondered about tech words i heard on barista shift, wich i didn't do it on the day. maybe check if the before-bed thoughts are properly assigned to the activities during that day

### Screenshots

![image](https://user-images.githubusercontent.com/65917165/147272749-5dfe691c-6424-4100-8ad0-f48debadd619.png)
![image](https://user-images.githubusercontent.com/65917165/147272794-c0ce2b80-6487-402e-9c94-8b7aada2bfe5.png)

**Comment by AgustinRamiroDiaz** [comment] 2021-12-23 23:20
@RuolinZheng08 the problem is in game/scripts/labels at line 129

`
if not has_triggered_ending_today:
        player smile "Hmmm... Let's see. Do I have any cool tech terms I caught during my barista shift that I need to research?"
`

Maybe change the phrase to something like 

`
if not has_triggered_ending_today:
        player smile "Hmmm... Let's see. Do I have any cool tech terms I caught during the day that I need to research?"
`

Or using the `day_activity` to generate the phrase

**Comment by RuolinZheng08** [comment] 2021-12-23 23:46
Fixed in https://github.com/freeCodeCamp/LearnToCodeRPG/commit/5484a5412fe95923bf5a57e47baa622f4d4cc255. Thanks!

**Closed by RuolinZheng08** 2021-12-23 23:46 UTC
